name: Windows MSVC

on: [push, pull_request]

jobs:
  build:
    name: Windows MSVC
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build
        run: >
          mkdir build;
          cd build;
          cmake ..
          -DCMAKE_CXX_COMPILER="cl"
          -DCMAKE_CXX_COMPILER="cl"
          -DMUGGLE_BUILD_SHARED_LIB=ON
          -DMUGGLE_BUILD_EXAMPLE=OFF
          -DMUGGLE_BUILD_TESTING=ON
          -DMUGGLE_BUILD_BENCHMARK=ON;
          cmake --build . --config Release;


      - name: tests
        run: >
          cd build;
          cmake --build . --target RUN_TESTS;
